Repository linea-it/tno, pull requests merged in 2020-07, with the labels that each got.

#479 Adding explicit summary of ccd plot
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
Labels: Feature

#480 Menu update: dropdown icon and item removal
  frontend/.eslintignore
  frontend/src/components/Chart/AstrometryTimeProfile.js
  frontend/src/components/Drawer/index.js
  frontend/src/components/Drawer/styles.js
  frontend/src/components/Stepper/index.js
  frontend/src/pages/Astrometry/Asteroid.js
  frontend/src/pages/Astrometry/Detail.js
  frontend/src/pages/Astrometry/index.js
  frontend/src/pages/BspJpl/index.js
  frontend/src/pages/JohnstonArchive/Detail.js
  frontend/src/pages/JohnstonArchive/index.js
  frontend/src/pages/OrbitalParameter/index.js
  frontend/src/pages/SearchSsso/Detail.js
  frontend/src/pages/SearchSsso/index.js
  frontend/src/pages/Skybot/index.js
  frontend/src/routes/index.js
  frontend/src/services/api/Praia.js
  frontend/src/services/api/Skybot.js
Labels: Feature

#481 Adding year control to calendar of exposures
  frontend/src/assets/img/linea-logo-mini.png
  frontend/src/assets/img/linea.png
  frontend/src/assets/img/loading.gif
  frontend/src/assets/img/loading.svg
  frontend/src/assets/img/logo-mini.png
  frontend/src/assets/img/logo.png
  frontend/src/components/Chart/CalendarExecutedNight.js
  frontend/src/components/Chart/CalendarHeatmap.js
  frontend/src/components/Drawer/index.js
  frontend/src/components/Footer/index.js
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
  frontend/src/pages/Skybot/styles.js
  frontend/src/themes/light.js
Labels: Feature

#482 Feat/skybot cancel job
  core_admin/des/models/skybot_jobs.py
  core_admin/des/skybot/import_positions.py
  core_admin/des/skybot/pipeline.py
  core_admin/des/views/skybot_job.py
  core_admin/skybot/import_positions.py
  core_admin/skybot/migrations/0003_position_created.py
  core_admin/skybot/migrations/0004_auto_20200629_2218.py
  core_admin/skybot/models/position.py
  frontend/src/pages/Skybot/Detail.js
  frontend/src/services/api/Skybot.js
Labels: Feature

#483 Fixed error in Skybot Calendar
  core_admin/des/dao/exposure.py
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/views/exposure.py
  core_admin/des/views/skybot_job_result.py
Labels: bug

#484 Fixes and features asked on validation
  frontend/src/components/Chart/CCD.js
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/index.js
Labels: Feature, bug

#487 Feat/download des ccds
  core_admin/common/download.py
  core_admin/common/unpack_fz.py
  core_admin/common/views.py
  core_admin/coreAdmin/settings.py
  core_admin/coreAdmin/urls.py
  core_admin/des/admin.py
  core_admin/des/apps.py
  core_admin/des/ccd/__init__.py
  core_admin/des/ccd/daemon.py
  core_admin/des/ccd/download.py
  core_admin/des/dao/__init__.py
  core_admin/des/dao/ccd.py
  core_admin/des/dao/download_ccd_job.py
  core_admin/des/dao/download_ccd_result.py
  core_admin/des/dao/skybot_position.py
  core_admin/des/migrations/0007_downloadccdjob.py
  core_admin/des/migrations/0008_auto_20200626_1853.py
  core_admin/des/migrations/0009_downloadccdjobresult.py
  core_admin/des/migrations/0010_auto_20200702_2045.py
  core_admin/des/migrations/0011_auto_20200702_2125.py
  core_admin/des/migrations/0012_auto_20200706_2003.py
  core_admin/des/migrations/0013_downloadccdjob_path.py
  core_admin/des/models/__init__.py
  core_admin/des/models/download_ccd_job.py
  core_admin/des/models/download_ccd_result.py
  core_admin/des/serializers/__init__.py
  core_admin/des/serializers/download_ccd_job.py
  core_admin/des/views/__init__.py
  core_admin/des/views/download_ccd_job.py
  core_admin/requirements.txt
Labels: Feature

#486 Fixing CCD count bug and some small changes asked in the last meeting
  core_admin/des/skybot/pipeline.py
  core_admin/des/views/skybot_job.py
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
Labels: Feature, bug, in Progress

#488 Download ccds calendar
  core_admin/des/ccd/daemon.py
  core_admin/des/ccd/download.py
  core_admin/des/dao/ccd.py
  core_admin/des/views/ccd.py
  core_admin/des/views/download_ccd_job.py
Labels: Feature

#489 Creating Download page and integrating with API
  core_admin/des/views/ccd.py
  frontend/.eslintignore
  frontend/src/components/Chart/CalendarExecutedCcd.js
  frontend/src/components/Chart/CcdsDownloadedGrouped.js
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Download/styles.js
  frontend/src/pages/Skybot/index.js
  frontend/src/routes/index.js
  frontend/src/services/api/Download.js
  frontend/src/services/api/Skybot.js
Labels: Feature

#492 Correction applied to the date_obs of the exposure.
  core_admin/common/views.py
  core_admin/des/migrations/0014_auto_20200720_1617.py
  core_admin/des/models/skybot_job_result.py
  core_admin/des/skybot/pipeline.py
Labels: Feature

#494 Fixed and features after Download page validation
  core_admin/des/views/exposure.py
  frontend/src/components/Chart/CcdsDownloadedGrouped.js
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Download/styles.js
  frontend/src/pages/Skybot/Detail.js
Labels: Feature, bug, in Progress

#496 More indicators have been added for a skybot job.
  core_admin/des/dao/skybot_job.py
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/migrations/0015_auto_20200727_2104.py
  core_admin/des/models/skybot_jobs.py
  core_admin/des/serializers/skybot_job.py
  core_admin/des/skybot/pipeline.py
Labels: Feature

#495 Fixes and improvements
  frontend/src/components/Chart/CCD.js
  frontend/src/components/Switch/index.js
  frontend/src/components/Switch/styles.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Download/styles.js
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
Labels: in Progress

#498 query for dynclas x asteroids
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/models/skybot_job_result.py
  core_admin/des/views/skybot_job.py
  core_admin/des/views/skybot_job_result.py
  core_admin/tno/db.py
Labels: Feature

#499 Total ccds per class has been added.
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/views/skybot_job_result.py
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/services/api/Skybot.js
Labels: Feature
