Repository linea-it/tno, pull requests merged in 2020-08, with the labels that each got.

#502 Added count of ccds with asteroids
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/migrations/0016_auto_20200730_2038.py
  core_admin/des/models/skybot_job_result.py
  core_admin/des/serializers/skybot_job_result.py
  core_admin/des/skybot/import_positions.py
  core_admin/des/skybot/pipeline.py
  frontend/src/pages/Skybot/Asteroid.js
Labels: Feature

#504 Summary ccds, asteroids and posicitions by class
  core_admin/common/views.py
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/skybot/pipeline.py
  core_admin/des/views/skybot_job.py
  core_admin/tno/db.py
Labels: Feature

#501 Fix/skybot and download validation
  core_admin/des/views/skybot_job_result.py
  frontend/src/components/Chart/CCD.js
  frontend/src/components/Chart/CcdsDownloadedGrouped.js
  frontend/src/components/Drawer/index.js
  frontend/src/components/Switch/index.js
  frontend/src/components/Switch/styles.js
  frontend/src/components/Table/ColumnStatus.js
  frontend/src/components/Table/index.js
  frontend/src/components/Table/styles.js
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Download/styles.js
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
  frontend/src/pages/Skybot/styles.js
  frontend/src/services/api/Skybot.js
Labels: Feature, bug

#505 Feat/download summary
  core_admin/des/dao/download_ccd_result.py
  core_admin/des/dao/skybot_position.py
  core_admin/des/views/ccd.py
  frontend/src/pages/Download/index.js
  frontend/src/services/api/Download.js
Labels: Feature

#506 Added count by bands in skybot summary
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/views/skybot_job.py
  frontend/src/pages/Skybot/Detail.js
Labels: Feature

#507 Meeting validation repairs and features
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Download/styles.js
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
Labels: Feature

#508 Fix/download estimated
  core_admin/des/admin.py
  core_admin/des/ccd/download.py
  core_admin/des/dao/ccd.py
  core_admin/des/dao/download_ccd_job.py
  core_admin/des/dao/skybot_position.py
  core_admin/des/migrations/0017_auto_20200819_1558.py
  core_admin/des/models/download_ccd_job.py
  core_admin/des/serializers/download_ccd_job.py
  core_admin/des/views/ccd.py
  core_admin/des/views/download_ccd_job.py
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
Labels: bug

#510 Added more information in skybot finish mail
  core_admin/common/templates/notification_skybot_finish.html
  core_admin/des/skybot/pipeline.py
Labels: enhancement

#511 Fixed summary of asteroids by dynclass
  core_admin/des/dao/skybot_job_result.py
  frontend/src/pages/Skybot/Detail.js
Labels: bug

#512 Added Total CCDs by class and by exposure
  core_admin/des/dao/skybot_job_result.py
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
Labels: Feature

#513 Added the band and date of observation of the exposure in the table…
  core_admin/des/serializers/skybot_job_result.py
  core_admin/des/views/skybot_job_result.py
  frontend/src/components/Table/index.js
  frontend/src/pages/Skybot/Detail.js
  frontend/src/services/api/Skybot.js
Labels: Feature

#515 Added an endpoint that returns the estimated execution time. and the …
  core_admin/des/dao/skybot_job_result.py
  core_admin/des/migrations/0018_skybotjob_estimated_execution_time.py
  core_admin/des/models/skybot_jobs.py
  core_admin/des/serializers/skybot_job.py
  core_admin/des/views/skybot_job.py
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
  frontend/src/services/api/Skybot.js
Labels: Feature

#514 LDAP Authentication and validation meeting requests
  core_admin/Dockerfile
  core_admin/coreAdmin/settings.py
  core_admin/requirements.txt
  env_template
  frontend/src/components/Table/index.js
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
Labels: Feature, enhancement

#517 Minor fix in estimated_time and dynclass counts
  core_admin/des/views/skybot_job.py
Labels: Feature

#519 Meeting validation repairs and features
  frontend/src/components/List/index.js
  frontend/src/components/List/styles.js
  frontend/src/components/Table/ColumnStatus.js
  frontend/src/components/Table/index.js
  frontend/src/components/Table/styles.js
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Download/styles.js
  frontend/src/pages/Skybot/Asteroid.js
  frontend/src/pages/Skybot/Detail.js
  frontend/src/pages/Skybot/index.js
Labels: Feature, bug

#518 Added fields to store the estimated time and job size.
  core_admin/des/ccd/download.py
  core_admin/des/dao/download_ccd_job.py
  core_admin/des/migrations/0019_auto_20200828_1716.py
  core_admin/des/models/download_ccd_job.py
  core_admin/des/serializers/download_ccd_job.py
  core_admin/des/views/download_ccd_job.py
  frontend/src/pages/Download/Detail.js
Labels: Feature

#520 Meeting validation repairs and features
  frontend/src/pages/Download/Detail.js
  frontend/src/pages/Download/index.js
  frontend/src/pages/Download/styles.js
  frontend/src/pages/Skybot/index.js
  frontend/src/pages/Skybot/styles.js
Labels: bug
